#!/bin/sh

DEV=/sys/bus/usb/devices/7-1

echo 0 > $DEV/power/autosuspend_delay_ms
echo auto > $DEV/power/control
cat $DEV/power/runtime_status
echo on  > $DEV/power/control
cat $DEV/power/runtime_status
