---
action: PrintConfig
devs:
  - dev: Usb
    chans:
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.0
        tags: ["r", "rgb", "window"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.9
        tags: ["b", "rgb", "window"]
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.4
        tags: ["g", "rgb", "window"]
  - dev:
      UdpV2:
        ip: 192.168.0.102
        port: 8932
        chans: 3
    chans:
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.3
        tags: ["bottom", "white", "wall"]
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.30
        tags: ["top", "white", "wall"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.27
        tags: ["bed", "white", "wall"]
  - dev:
      UdpV2:
        ip: 192.168.0.100
        port: 8932
        chans: 3
    chans:
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.2
        tags: ["test", "test1", "ceiling", "ceiling1"]
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.20
        tags: ["test", "test2", "spotlight"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.2
        tags: ["test", "test3", "ceiling", "ceiling2"]
