---
action: PrintConfig
devs:
  - dev: Usb
    chans:
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.8
        tags: ["Red"]
      - index: 1
        min: 0.002
        max: 1.0
        exp: 1.9
        tags: ["Blue"]
      - index: 2
        min: 0.0001
        max: 1.0
        exp: 3.7
        tags: ["Green"]
  - dev:
      UdpV2:
        ip: 192.168.0.111
        port: 8932
        chans: 3
    chans:
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.27
        tags: ["Bed"]
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.30
        tags: ["Top"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.7
        tags: ["Bottom"]
