---
action: PrintConfig
devs:
  - dev: Usb
    chans:
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.0
        tags: ["r", "rgb", "window"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.9
        tags: ["b", "rgb", "window"]
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.4
        tags: ["g", "rgb", "window"]
  - dev:
      UdpV2:
        ip: 192.168.0.111
        port: 8932
        chans: 3
    chans:
      - index: 0
        min: 0.0
        max: 1.0
        exp: 2.27
        tags: ["bed", "white", "wall"]
      - index: 2
        min: 0.0
        max: 1.0
        exp: 2.30
        tags: ["top", "white", "wall"]
      - index: 1
        min: 0.0
        max: 1.0
        exp: 2.7
        tags: ["bottom", "white", "wall"]
